site_name: db-migrate
nav:
  - Search through the docs: search.html
  - Home: index.md
  - "Helping db-migrate": help.md
  - Getting Started:
      - Installation: Getting Started/installation.md
      - Configuration: Getting Started/configuration.md
      - "The Commands": Getting Started/the commands.md
      - Usage: Getting Started/usage.md
  - API:
      - "Generic Datatypes": API/generic datatypes.md
      - "SQL API": API/SQL.md
      - "NoSQL API": API/NoSQL.md
  - Developers:
      - "Running Tests": Developers/running tests.md
      - Contributing: Developers/contributing.md
docs_dir: .
repo_url: https://github.com/db-migrate/english-docs
theme: readthedocs
